

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_test?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
#在配置文件中配置spring.aop.proxy-target-class为false这为使用jdk动态代理。该配置默认值为true，代表使用cglib动态代理。
  aop:
    proxy-target-class: true
  redis:
    host: 127.0.0.1 #redis服务器ip地址
    port: 6379  #redis端口号
#配置激活哪个环境。如果端口号为application-test.yml配置的端口号，则说明激活成功
  profiles:
    active: test

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径。表示mapper目录下的所有以Mapper.xml结尾的类
  type-aliases-package: com.hkvszk.springbootweb.domain   # 配置哪个包下的类有默认的别名

#80端口访问的时候可以不写端口号。
#因为TOMCAT默认的访问端口为8080，而TCP/IP协议默认80端口访问，大家之所以看到别的网站都不写端口号是因为人家用的的80端口访问的，而80端口因为的TCP/IP的默认端口所以就不用写出来了。
server:
  port: 80

#debug: true #开启日志
#logging:
#  level:
#    com.hkvszk.springbootweb: debug #设置日志级别